version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

# version: '3'

# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: mysql:5.7
#     container_name: db
#     ports:
#         - "33061:3306"
#     # command: --init-file /data/application/init.sql
#     restart: always
#     # volumes:
#         # - "database_data:/var/lib/mysql"
#         # - ./init.sql:/data/application/init.sql
#     environment:
#         MYSQL_ROOT_USER: root
#         MYSQL_ROOT_PASSWORD: secret
#         MYSQL_DATABASE: homestead
#         MYSQL_USER: root
#         MYSQL_PASSWORD: secret
# ###< doctrine/doctrine-bundle ###
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: pma
#     links:
#       - database
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#     restart: always
#     ports:
#       - 8081:80
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "9999:80"
#     volumes:
#       - /var/www/html:/usr/share/nginx/html
#     restart: always
# volumes:
###> doctrine/doctrine-bundle ###
  # database_data:
###< doctrine/doctrine-bundle ###
