version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
        - "33306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: guestbook
###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    restart: always
    links:
      - database
    ports:
      - 8080:8080
volumes:
  mysql-data:
###> doctrine/doctrine-bundle ###
