version: '3'

services:
  database:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbook
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - '8030:80'
      environment:
        PMA_HOST: database
      depends_on:
        - database
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database  
    links:
      - php-fpm
      - database
  php-fpm:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
volumes:
  mysql-data:
