controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
image_show:
    path: /images/{imageName}
    controller: App\Controller\ImageController::showImageAction
    requirements:
        imageName: '.+'
