<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNWSwr0t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNWSwr0t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNWSwr0t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNWSwr0t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNWSwr0t\App_KernelDevDebugContainer([
    'container.build_hash' => 'NWSwr0t',
    'container.build_id' => '78d095f7',
    'container.build_time' => 1692733810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNWSwr0t');
